// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKR9IgjGXKampuiEnI0cYC1ZLRjRoLW0',
    appId: '1:426307365530:web:70aa133ce5286f988c4d23',
    messagingSenderId: '426307365530',
    projectId: 'bookflutterapp',
    authDomain: 'bookflutterapp.firebaseapp.com',
    storageBucket: 'bookflutterapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLc8QoanGTaXciQQXuQemuqQwxklaCxjQ',
    appId: '1:426307365530:android:ae548e0cda5b22038c4d23',
    messagingSenderId: '426307365530',
    projectId: 'bookflutterapp',
    storageBucket: 'bookflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFTM9j1pgmrigkkVseo-eSpzM5zHrGzk',
    appId: '1:426307365530:ios:f0bd6a4d58b54e4e8c4d23',
    messagingSenderId: '426307365530',
    projectId: 'bookflutterapp',
    storageBucket: 'bookflutterapp.appspot.com',
    iosClientId: '426307365530-6ifdf35n3ej2savu86u73g2edfuvmsst.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFTM9j1pgmrigkkVseo-eSpzM5zHrGzk',
    appId: '1:426307365530:ios:f0bd6a4d58b54e4e8c4d23',
    messagingSenderId: '426307365530',
    projectId: 'bookflutterapp',
    storageBucket: 'bookflutterapp.appspot.com',
    iosClientId: '426307365530-6ifdf35n3ej2savu86u73g2edfuvmsst.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
